openapi: 3.0.0
info:
  title: Node - Express - TS - API DOC
  description: GC - Demo API documentation.
  version: 1.0.0
  
servers:
  - url: http://localhost:3000/v1/
    description: Access api's from localhost
  - url:  http://staging-api.com/v1/
    description: Access api's from server

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /users/get-user-dtls:
    get:
      summary: Returns users details.
      description: Returns users details using userid.
  
      # parameters:
        #  userId: '6213680af0c5b922101689e9'
      responses:
        '200':    # status code
          description: returns a user object
          content:
            application/json:
              schema: 
                type: object
              